### ISSUE TITLE
Serverless sls lambda error

### ISSUE THREAD

**Issue by msimonc** [aheckmann/node-ses#64]
I can send emails local dev but when I deploy Cloudwatch logs are:

RequestError NodeSesInternal Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:608:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1514:19)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: null,
  host: 'email.ap-southeast-2.amazonaws.com',
  port: 443,
  localAddress: undefined

?, thanks!

**Comment by markstos** [comment]
I'm closing this because it's an environmental problem. As you pointed out, it works locally. You should check our related IAM policies for your Lambda.
